services:
  - type: worker
    name: primaryclasses-telegram-bot
    runtime: node
    repo: https://github.com/ugafforov/primaryclasses
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: TZ
        value: Asia/Tashkent
